/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rivora Exchange API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  BankDetails,
  ChangePasswordRequest,
  CreateDepositRequestBody,
  CreateInvestmentPlanRequest,
  CreateInvestmentRequest,
  CreateWithdrawalRequestBody,
  DepositRequest,
  ErrorResponse,
  InvestmentPlan,
  ListDepositRequestsParams,
  ListInvestmentPlansParams,
  ListInvestmentsParams,
  ListTransactionsParams,
  ListUsersParams,
  ListWithdrawalRequestsParams,
  LoginRequest,
  RegisterRequest,
  Transaction,
  UpdateInvestmentPlanRequest,
  UpdateRequestStatusBody,
  UpdateUserRequest,
  User,
  UserInvestment,
  WithdrawalRequest
} from './models';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getRegisterUrl = () => {


  

  return `/auth/register`
}

export const register = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<AuthResponse> => {
  
  return customFetch<AuthResponse>(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}




export const getRegisterMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterRequest>}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: BodyType<RegisterRequest>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = BodyType<RegisterRequest>
    export type RegisterMutationError = ErrorType<ErrorResponse>

    export const useRegister = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: BodyType<RegisterRequest>},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getLoginUrl = () => {


  

  return `/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<AuthResponse> => {
  
  return customFetch<AuthResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequest>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginRequest>
    export type LoginMutationError = ErrorType<ErrorResponse>

    export const useLogin = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginRequest>},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getLogoutUrl = () => {


  

  return `/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = ErrorType<unknown>

    export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getGetMeUrl = () => {


  

  return `/auth/me`
}

export const getMe = async ( options?: RequestInit): Promise<User> => {
  
  return customFetch<User>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<ErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<ErrorResponse>



export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getChangePasswordUrl = () => {


  

  return `/auth/change-password`
}

export const changePassword = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<User> => {
  
  return customFetch<User>(getChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordRequest,)
  }
);}




export const getChangePasswordMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: BodyType<ChangePasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = BodyType<ChangePasswordRequest>
    export type ChangePasswordMutationError = ErrorType<ErrorResponse>

    export const useChangePassword = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: BodyType<ChangePasswordRequest>},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getUpdateMyBankDetailsUrl = () => {


  

  return `/users/me/bank`
}

export const updateMyBankDetails = async (bankDetails: BankDetails, options?: RequestInit): Promise<User> => {
  
  return customFetch<User>(getUpdateMyBankDetailsUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bankDetails,)
  }
);}




export const getUpdateMyBankDetailsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyBankDetails>>, TError,{data: BodyType<BankDetails>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMyBankDetails>>, TError,{data: BodyType<BankDetails>}, TContext> => {

const mutationKey = ['updateMyBankDetails'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMyBankDetails>>, {data: BodyType<BankDetails>}> = (props) => {
          const {data} = props ?? {};

          return  updateMyBankDetails(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMyBankDetailsMutationResult = NonNullable<Awaited<ReturnType<typeof updateMyBankDetails>>>
    export type UpdateMyBankDetailsMutationBody = BodyType<BankDetails>
    export type UpdateMyBankDetailsMutationError = ErrorType<unknown>

    export const useUpdateMyBankDetails = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyBankDetails>>, TError,{data: BodyType<BankDetails>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateMyBankDetails>>,
        TError,
        {data: BodyType<BankDetails>},
        TContext
      > => {

      const mutationOptions = getUpdateMyBankDetailsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getListUsersUrl = (params?: ListUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

export const listUsers = async (params?: ListUsersParams, options?: RequestInit): Promise<User[]> => {
  
  return customFetch<User[]>(getListUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListUsersQueryKey = (params?: ListUsersParams,) => {
    return [
    `/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<unknown>>(params?: ListUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = ErrorType<unknown>



export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<unknown>>(
 params?: ListUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListUsersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getGetUserUrl = (userId: string,) => {


  

  return `/users/${userId}`
}

export const getUser = async (userId: string, options?: RequestInit): Promise<User> => {
  
  return customFetch<User>(getGetUserUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserQueryKey = (userId?: string,) => {
    return [
    `/users/${userId}`
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ErrorResponse>>(userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(userId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = ErrorType<ErrorResponse>



export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ErrorResponse>>(
 userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getUpdateUserUrl = (userId: string,) => {


  

  return `/users/${userId}`
}

export const updateUser = async (userId: string,
    updateUserRequest: UpdateUserRequest, options?: RequestInit): Promise<User> => {
  
  return customFetch<User>(getUpdateUserUrl(userId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserRequest,)
  }
);}




export const getUpdateUserMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{userId: string;data: BodyType<UpdateUserRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{userId: string;data: BodyType<UpdateUserRequest>}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {userId: string;data: BodyType<UpdateUserRequest>}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateUser(userId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = BodyType<UpdateUserRequest>
    export type UpdateUserMutationError = ErrorType<ErrorResponse>

    export const useUpdateUser = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{userId: string;data: BodyType<UpdateUserRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {userId: string;data: BodyType<UpdateUserRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getListInvestmentPlansUrl = (params?: ListInvestmentPlansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/investment-plans?${stringifiedParams}` : `/investment-plans`
}

export const listInvestmentPlans = async (params?: ListInvestmentPlansParams, options?: RequestInit): Promise<InvestmentPlan[]> => {
  
  return customFetch<InvestmentPlan[]>(getListInvestmentPlansUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListInvestmentPlansQueryKey = (params?: ListInvestmentPlansParams,) => {
    return [
    `/investment-plans`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListInvestmentPlansQueryOptions = <TData = Awaited<ReturnType<typeof listInvestmentPlans>>, TError = ErrorType<unknown>>(params?: ListInvestmentPlansParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listInvestmentPlans>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInvestmentPlansQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInvestmentPlans>>> = ({ signal }) => listInvestmentPlans(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInvestmentPlans>>, TError, TData> & { queryKey: QueryKey }
}

export type ListInvestmentPlansQueryResult = NonNullable<Awaited<ReturnType<typeof listInvestmentPlans>>>
export type ListInvestmentPlansQueryError = ErrorType<unknown>



export function useListInvestmentPlans<TData = Awaited<ReturnType<typeof listInvestmentPlans>>, TError = ErrorType<unknown>>(
 params?: ListInvestmentPlansParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listInvestmentPlans>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListInvestmentPlansQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getCreateInvestmentPlanUrl = () => {


  

  return `/investment-plans`
}

export const createInvestmentPlan = async (createInvestmentPlanRequest: CreateInvestmentPlanRequest, options?: RequestInit): Promise<InvestmentPlan> => {
  
  return customFetch<InvestmentPlan>(getCreateInvestmentPlanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInvestmentPlanRequest,)
  }
);}




export const getCreateInvestmentPlanMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvestmentPlan>>, TError,{data: BodyType<CreateInvestmentPlanRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createInvestmentPlan>>, TError,{data: BodyType<CreateInvestmentPlanRequest>}, TContext> => {

const mutationKey = ['createInvestmentPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvestmentPlan>>, {data: BodyType<CreateInvestmentPlanRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createInvestmentPlan(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateInvestmentPlanMutationResult = NonNullable<Awaited<ReturnType<typeof createInvestmentPlan>>>
    export type CreateInvestmentPlanMutationBody = BodyType<CreateInvestmentPlanRequest>
    export type CreateInvestmentPlanMutationError = ErrorType<unknown>

    export const useCreateInvestmentPlan = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvestmentPlan>>, TError,{data: BodyType<CreateInvestmentPlanRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createInvestmentPlan>>,
        TError,
        {data: BodyType<CreateInvestmentPlanRequest>},
        TContext
      > => {

      const mutationOptions = getCreateInvestmentPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getUpdateInvestmentPlanUrl = (planId: string,) => {


  

  return `/investment-plans/${planId}`
}

export const updateInvestmentPlan = async (planId: string,
    updateInvestmentPlanRequest: UpdateInvestmentPlanRequest, options?: RequestInit): Promise<InvestmentPlan> => {
  
  return customFetch<InvestmentPlan>(getUpdateInvestmentPlanUrl(planId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateInvestmentPlanRequest,)
  }
);}




export const getUpdateInvestmentPlanMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateInvestmentPlan>>, TError,{planId: string;data: BodyType<UpdateInvestmentPlanRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateInvestmentPlan>>, TError,{planId: string;data: BodyType<UpdateInvestmentPlanRequest>}, TContext> => {

const mutationKey = ['updateInvestmentPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateInvestmentPlan>>, {planId: string;data: BodyType<UpdateInvestmentPlanRequest>}> = (props) => {
          const {planId,data} = props ?? {};

          return  updateInvestmentPlan(planId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateInvestmentPlanMutationResult = NonNullable<Awaited<ReturnType<typeof updateInvestmentPlan>>>
    export type UpdateInvestmentPlanMutationBody = BodyType<UpdateInvestmentPlanRequest>
    export type UpdateInvestmentPlanMutationError = ErrorType<ErrorResponse>

    export const useUpdateInvestmentPlan = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateInvestmentPlan>>, TError,{planId: string;data: BodyType<UpdateInvestmentPlanRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateInvestmentPlan>>,
        TError,
        {planId: string;data: BodyType<UpdateInvestmentPlanRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateInvestmentPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getDeleteInvestmentPlanUrl = (planId: string,) => {


  

  return `/investment-plans/${planId}`
}

export const deleteInvestmentPlan = async (planId: string, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getDeleteInvestmentPlanUrl(planId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteInvestmentPlanMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteInvestmentPlan>>, TError,{planId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteInvestmentPlan>>, TError,{planId: string}, TContext> => {

const mutationKey = ['deleteInvestmentPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteInvestmentPlan>>, {planId: string}> = (props) => {
          const {planId} = props ?? {};

          return  deleteInvestmentPlan(planId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteInvestmentPlanMutationResult = NonNullable<Awaited<ReturnType<typeof deleteInvestmentPlan>>>
    
    export type DeleteInvestmentPlanMutationError = ErrorType<ErrorResponse>

    export const useDeleteInvestmentPlan = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteInvestmentPlan>>, TError,{planId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteInvestmentPlan>>,
        TError,
        {planId: string},
        TContext
      > => {

      const mutationOptions = getDeleteInvestmentPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getListInvestmentsUrl = (params?: ListInvestmentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/investments?${stringifiedParams}` : `/investments`
}

export const listInvestments = async (params?: ListInvestmentsParams, options?: RequestInit): Promise<UserInvestment[]> => {
  
  return customFetch<UserInvestment[]>(getListInvestmentsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListInvestmentsQueryKey = (params?: ListInvestmentsParams,) => {
    return [
    `/investments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListInvestmentsQueryOptions = <TData = Awaited<ReturnType<typeof listInvestments>>, TError = ErrorType<unknown>>(params?: ListInvestmentsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listInvestments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListInvestmentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listInvestments>>> = ({ signal }) => listInvestments(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listInvestments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListInvestmentsQueryResult = NonNullable<Awaited<ReturnType<typeof listInvestments>>>
export type ListInvestmentsQueryError = ErrorType<unknown>



export function useListInvestments<TData = Awaited<ReturnType<typeof listInvestments>>, TError = ErrorType<unknown>>(
 params?: ListInvestmentsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listInvestments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListInvestmentsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getCreateInvestmentUrl = () => {


  

  return `/investments`
}

export const createInvestment = async (createInvestmentRequest: CreateInvestmentRequest, options?: RequestInit): Promise<UserInvestment> => {
  
  return customFetch<UserInvestment>(getCreateInvestmentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInvestmentRequest,)
  }
);}




export const getCreateInvestmentMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvestment>>, TError,{data: BodyType<CreateInvestmentRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createInvestment>>, TError,{data: BodyType<CreateInvestmentRequest>}, TContext> => {

const mutationKey = ['createInvestment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvestment>>, {data: BodyType<CreateInvestmentRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createInvestment(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateInvestmentMutationResult = NonNullable<Awaited<ReturnType<typeof createInvestment>>>
    export type CreateInvestmentMutationBody = BodyType<CreateInvestmentRequest>
    export type CreateInvestmentMutationError = ErrorType<ErrorResponse>

    export const useCreateInvestment = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvestment>>, TError,{data: BodyType<CreateInvestmentRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createInvestment>>,
        TError,
        {data: BodyType<CreateInvestmentRequest>},
        TContext
      > => {

      const mutationOptions = getCreateInvestmentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getListDepositRequestsUrl = (params?: ListDepositRequestsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/deposit-requests?${stringifiedParams}` : `/deposit-requests`
}

export const listDepositRequests = async (params?: ListDepositRequestsParams, options?: RequestInit): Promise<DepositRequest[]> => {
  
  return customFetch<DepositRequest[]>(getListDepositRequestsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListDepositRequestsQueryKey = (params?: ListDepositRequestsParams,) => {
    return [
    `/deposit-requests`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListDepositRequestsQueryOptions = <TData = Awaited<ReturnType<typeof listDepositRequests>>, TError = ErrorType<unknown>>(params?: ListDepositRequestsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDepositRequests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDepositRequestsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDepositRequests>>> = ({ signal }) => listDepositRequests(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDepositRequests>>, TError, TData> & { queryKey: QueryKey }
}

export type ListDepositRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof listDepositRequests>>>
export type ListDepositRequestsQueryError = ErrorType<unknown>



export function useListDepositRequests<TData = Awaited<ReturnType<typeof listDepositRequests>>, TError = ErrorType<unknown>>(
 params?: ListDepositRequestsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listDepositRequests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListDepositRequestsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getCreateDepositRequestUrl = () => {


  

  return `/deposit-requests`
}

export const createDepositRequest = async (createDepositRequestBody: CreateDepositRequestBody, options?: RequestInit): Promise<DepositRequest> => {
  
  return customFetch<DepositRequest>(getCreateDepositRequestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDepositRequestBody,)
  }
);}




export const getCreateDepositRequestMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDepositRequest>>, TError,{data: BodyType<CreateDepositRequestBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createDepositRequest>>, TError,{data: BodyType<CreateDepositRequestBody>}, TContext> => {

const mutationKey = ['createDepositRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDepositRequest>>, {data: BodyType<CreateDepositRequestBody>}> = (props) => {
          const {data} = props ?? {};

          return  createDepositRequest(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDepositRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createDepositRequest>>>
    export type CreateDepositRequestMutationBody = BodyType<CreateDepositRequestBody>
    export type CreateDepositRequestMutationError = ErrorType<ErrorResponse>

    export const useCreateDepositRequest = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDepositRequest>>, TError,{data: BodyType<CreateDepositRequestBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createDepositRequest>>,
        TError,
        {data: BodyType<CreateDepositRequestBody>},
        TContext
      > => {

      const mutationOptions = getCreateDepositRequestMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getUpdateDepositRequestUrl = (requestId: string,) => {


  

  return `/deposit-requests/${requestId}`
}

export const updateDepositRequest = async (requestId: string,
    updateRequestStatusBody: UpdateRequestStatusBody, options?: RequestInit): Promise<DepositRequest> => {
  
  return customFetch<DepositRequest>(getUpdateDepositRequestUrl(requestId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRequestStatusBody,)
  }
);}




export const getUpdateDepositRequestMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDepositRequest>>, TError,{requestId: string;data: BodyType<UpdateRequestStatusBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDepositRequest>>, TError,{requestId: string;data: BodyType<UpdateRequestStatusBody>}, TContext> => {

const mutationKey = ['updateDepositRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDepositRequest>>, {requestId: string;data: BodyType<UpdateRequestStatusBody>}> = (props) => {
          const {requestId,data} = props ?? {};

          return  updateDepositRequest(requestId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDepositRequestMutationResult = NonNullable<Awaited<ReturnType<typeof updateDepositRequest>>>
    export type UpdateDepositRequestMutationBody = BodyType<UpdateRequestStatusBody>
    export type UpdateDepositRequestMutationError = ErrorType<ErrorResponse>

    export const useUpdateDepositRequest = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDepositRequest>>, TError,{requestId: string;data: BodyType<UpdateRequestStatusBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateDepositRequest>>,
        TError,
        {requestId: string;data: BodyType<UpdateRequestStatusBody>},
        TContext
      > => {

      const mutationOptions = getUpdateDepositRequestMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getListWithdrawalRequestsUrl = (params?: ListWithdrawalRequestsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/withdrawal-requests?${stringifiedParams}` : `/withdrawal-requests`
}

export const listWithdrawalRequests = async (params?: ListWithdrawalRequestsParams, options?: RequestInit): Promise<WithdrawalRequest[]> => {
  
  return customFetch<WithdrawalRequest[]>(getListWithdrawalRequestsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListWithdrawalRequestsQueryKey = (params?: ListWithdrawalRequestsParams,) => {
    return [
    `/withdrawal-requests`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListWithdrawalRequestsQueryOptions = <TData = Awaited<ReturnType<typeof listWithdrawalRequests>>, TError = ErrorType<unknown>>(params?: ListWithdrawalRequestsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWithdrawalRequests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWithdrawalRequestsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWithdrawalRequests>>> = ({ signal }) => listWithdrawalRequests(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWithdrawalRequests>>, TError, TData> & { queryKey: QueryKey }
}

export type ListWithdrawalRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof listWithdrawalRequests>>>
export type ListWithdrawalRequestsQueryError = ErrorType<unknown>



export function useListWithdrawalRequests<TData = Awaited<ReturnType<typeof listWithdrawalRequests>>, TError = ErrorType<unknown>>(
 params?: ListWithdrawalRequestsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWithdrawalRequests>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListWithdrawalRequestsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getCreateWithdrawalRequestUrl = () => {


  

  return `/withdrawal-requests`
}

export const createWithdrawalRequest = async (createWithdrawalRequestBody: CreateWithdrawalRequestBody, options?: RequestInit): Promise<WithdrawalRequest> => {
  
  return customFetch<WithdrawalRequest>(getCreateWithdrawalRequestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWithdrawalRequestBody,)
  }
);}




export const getCreateWithdrawalRequestMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWithdrawalRequest>>, TError,{data: BodyType<CreateWithdrawalRequestBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createWithdrawalRequest>>, TError,{data: BodyType<CreateWithdrawalRequestBody>}, TContext> => {

const mutationKey = ['createWithdrawalRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWithdrawalRequest>>, {data: BodyType<CreateWithdrawalRequestBody>}> = (props) => {
          const {data} = props ?? {};

          return  createWithdrawalRequest(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWithdrawalRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createWithdrawalRequest>>>
    export type CreateWithdrawalRequestMutationBody = BodyType<CreateWithdrawalRequestBody>
    export type CreateWithdrawalRequestMutationError = ErrorType<ErrorResponse>

    export const useCreateWithdrawalRequest = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWithdrawalRequest>>, TError,{data: BodyType<CreateWithdrawalRequestBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createWithdrawalRequest>>,
        TError,
        {data: BodyType<CreateWithdrawalRequestBody>},
        TContext
      > => {

      const mutationOptions = getCreateWithdrawalRequestMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getUpdateWithdrawalRequestUrl = (requestId: string,) => {


  

  return `/withdrawal-requests/${requestId}`
}

export const updateWithdrawalRequest = async (requestId: string,
    updateRequestStatusBody: UpdateRequestStatusBody, options?: RequestInit): Promise<WithdrawalRequest> => {
  
  return customFetch<WithdrawalRequest>(getUpdateWithdrawalRequestUrl(requestId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRequestStatusBody,)
  }
);}




export const getUpdateWithdrawalRequestMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWithdrawalRequest>>, TError,{requestId: string;data: BodyType<UpdateRequestStatusBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateWithdrawalRequest>>, TError,{requestId: string;data: BodyType<UpdateRequestStatusBody>}, TContext> => {

const mutationKey = ['updateWithdrawalRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWithdrawalRequest>>, {requestId: string;data: BodyType<UpdateRequestStatusBody>}> = (props) => {
          const {requestId,data} = props ?? {};

          return  updateWithdrawalRequest(requestId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWithdrawalRequestMutationResult = NonNullable<Awaited<ReturnType<typeof updateWithdrawalRequest>>>
    export type UpdateWithdrawalRequestMutationBody = BodyType<UpdateRequestStatusBody>
    export type UpdateWithdrawalRequestMutationError = ErrorType<ErrorResponse>

    export const useUpdateWithdrawalRequest = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWithdrawalRequest>>, TError,{requestId: string;data: BodyType<UpdateRequestStatusBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateWithdrawalRequest>>,
        TError,
        {requestId: string;data: BodyType<UpdateRequestStatusBody>},
        TContext
      > => {

      const mutationOptions = getUpdateWithdrawalRequestMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export const getListTransactionsUrl = (params?: ListTransactionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/transactions?${stringifiedParams}` : `/transactions`
}

export const listTransactions = async (params?: ListTransactionsParams, options?: RequestInit): Promise<Transaction[]> => {
  
  return customFetch<Transaction[]>(getListTransactionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListTransactionsQueryKey = (params?: ListTransactionsParams,) => {
    return [
    `/transactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof listTransactions>>, TError = ErrorType<unknown>>(params?: ListTransactionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTransactions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTransactionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTransactions>>> = ({ signal }) => listTransactions(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTransactions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof listTransactions>>>
export type ListTransactionsQueryError = ErrorType<unknown>



export function useListTransactions<TData = Awaited<ReturnType<typeof listTransactions>>, TError = ErrorType<unknown>>(
 params?: ListTransactionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTransactions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

// Referral team endpoint
export const getListMyReferralsUrl = () => {
  return `/users/me/referrals`
}

export const listMyReferrals = async ( options?: RequestInit): Promise<User[]> => {
  return customFetch<User[]>(getListMyReferralsUrl(),
  {
    ...options,
    method: 'GET'
  }
);}

export const getListMyReferralsQueryKey = () => {
    return [
    `/users/me/referrals`
    ] as const;
    }

export const getListMyReferralsQueryOptions = <TData = Awaited<ReturnType<typeof listMyReferrals>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMyReferrals>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {
  const {query: queryOptions, request: requestOptions} = options ?? {};
  const queryKey =  queryOptions?.queryKey ?? getListMyReferralsQueryKey();
  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyReferrals>>> = ({ signal }) => listMyReferrals({ signal, ...requestOptions });
  return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyReferrals>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMyReferralsQueryResult = NonNullable<Awaited<ReturnType<typeof listMyReferrals>>>
export type ListMyReferralsQueryError = ErrorType<unknown>

export function useListMyReferrals<TData = Awaited<ReturnType<typeof listMyReferrals>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMyReferrals>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMyReferralsQueryOptions(options)
  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };
  query.queryKey = queryOptions.queryKey ;
  return query;
}
